-- Codego Phase 1 Integration Schema

CREATE TABLE IF NOT EXISTS public.codego_cardholders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    codego_user_id TEXT, -- The userId returned by Codego
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    wallet_address TEXT, -- The DeFi wallet generated by Codego
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id)
);

CREATE TABLE IF NOT EXISTS public.codego_cards (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    codego_card_id TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL, -- virtual or physical
    status TEXT DEFAULT 'active', -- active, locked, canceled
    masked_pan TEXT NOT NULL,
    expiry_month INTEGER NOT NULL,
    expiry_year INTEGER NOT NULL,
    display_name TEXT,
    limit_amount NUMERIC,
    limit_frequency TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.codego_transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    card_id UUID NOT NULL REFERENCES public.codego_cards(id) ON DELETE CASCADE,
    codego_tx_id TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,
    status TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    currency TEXT NOT NULL,
    local_amount NUMERIC,
    local_currency TEXT,
    merchant_name TEXT,
    merchant_category_code TEXT,
    merchant_country TEXT,
    posted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE public.codego_cardholders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.codego_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.codego_transactions ENABLE ROW LEVEL SECURITY;

-- Cardholders: Users can read their own
CREATE POLICY "Users can view own codego_cardholders" 
ON public.codego_cardholders FOR SELECT 
USING (auth.uid() = user_id);

-- Cards: Users can read their own
CREATE POLICY "Users can view own codego_cards" 
ON public.codego_cards FOR SELECT 
USING (auth.uid() = user_id);

-- Transactions: Users can read their own
CREATE POLICY "Users can view own codego_transactions" 
ON public.codego_transactions FOR SELECT 
USING (auth.uid() = user_id);

-- Only service role can insert/update/delete these tables (via Edge Functions)
